version: "3.1"
services:
  mongo:
    image: "mongo"
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "mongo:/data/db"
  mongo-express:
      image: mongo-express
      depends_on:
          - mongo
      ports:
        - "27018:8081"
volumes:
  mongo:
