version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "postgres"
    ports:
      - "54320:5432"
    volumes:
      - postgres_dbdata:/var/lib/postgresql/data
volumes:
  postgres_dbdata:
